# requiring the environment of NodeJS 10
image: ubuntu:16.04

before_script:
   ##
   ## Install ssh-agent if not already installed, it is required by Docker.
   ## (change apt-get to yum if you use an RPM-based image)
   ##
   - apt-get update -y
   - apt-get install apt-transport-https wget lsb-release -y
   - rm /etc/apt/sources.list
   - wget https://isrc.iscas.ac.cn/mirror/help/mirror/xlab_ubuntu16.04.list -O /etc/apt/sources.list.d/xlab_ubuntu16.04.list
   - wget -qO - https://isrc.iscas.ac.cn/mirror/ros/ros.gpg | apt-key add -
   - sh -c 'echo "deb https://isrc.iscas.ac.cn/mirror/ros/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
   - wget -qO - https://isrc.iscas.ac.cn/mirror/xbot/xbot.gpg | apt-key add -
   - wget https://isrc.iscas.ac.cn/mirror/help/mirror/xbot-xenial-test-amd64.list -O /etc/apt/sources.list.d/xbot-xenial-test-amd64.list
   - apt-get update -y
   - apt-get install -y openssh-client dpkg-dev devscripts build-essential equivs

   ##
   ## Run ssh-agent (inside the build environment)
   ##
   - eval $(ssh-agent -s)

   ##
   ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
   ## We're using tr to fix line endings which makes ed25519 keys work
   ## without extra base64 encoding.
   ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
   ##
  #  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   ##
   ## Create the SSH directory and give it the right permissions
   ##
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   ##
   ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
   ## following two lines.
   ##
  #  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  #  - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  tags:
    - xeniel
  script:
    - cd xbot/xbot_bringup
    - mk-build-deps
    - sudo dpkg -i *.deb
    - dpkg-buildpackage -rfackeroot -uc -us
  only:
    - imudown
